behaviors:
  Drive:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 102400
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.1
        demo_path: Demos/Drive.demo
        use_actions: true
        use_vail: false
    behavioral_cloning:
      strength: 0.1
      demo_path: Demos/Drive.demo
    max_steps: 100000
    time_horizon: 64
    summary_freq: 10000